// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqwrhilqbckphfzznvcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxd3JoaWxxYmNrcGhmenpudmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjY5MDYsImV4cCI6MjA3MjEwMjkwNn0.U_8PT0M1sU6uG8_7kKel1xSRU9BfZNKwft5d-sWSVOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});